ProjectSupportingSystem/urls.py
from django.conf.urls import url, include
from users.views import IndexView, FormTestView
from django.views.static import serve
from ProjectSupportingSystem.settings import MEDIA_ROOT
import xadmin

urlpatterns = [
    url('^$', IndexView.as_view(), name="index"),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^project/', include('projects.urls', namespace="project")),
    url(r'^weekreport/', include('weekreports.urls', namespace="weekreport")),
    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    url('^formtest$', FormTestView.as_view(), name="formtest"),

]

apps/projects/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from .views import MyProjectsListView, CreateProjectStepOneView, ProjectDetailView, MissionDetailView, TestTreeView, MyMissionsListView
urlpatterns = [
    url(r'^ownlist/$', MyProjectsListView.as_view(), name='own_project_list'),
    url(r'^ownmissionslist/$', MyMissionsListView.as_view(), name='own_mission_list'),
    url(r'^add/$', CreateProjectStepOneView.as_view(), name='project_add'),
    url(r'^detail/(?P<project_id>\d+)/$', ProjectDetailView.as_view(), name='project_detail'),
    url(r'^mission_detail/(?P<mission_id>\d+)/$', MissionDetailView.as_view(), name='project_mission_detail'),
    url(r'^tree/$', TestTreeView.as_view(), name='test_tree'),
]

apps/users/forms.py
# -*- coding: utf-8 -*-
from django import forms


class NewProjectForm(forms.Form):
    """
    user = models.ManyToManyField(UserProfile, verbose_name="项目主要开发者")
    name = models.CharField(max_length=30, null=True, blank=True, verbose_name="项目名称")
    field = models.CharField(max_length=30, choices=PROJECT_FIELD, default="未设置", verbose_name="项目类型")
    status = models.CharField(max_length=30, choices=PROJECT_STATUS, default="未开始", verbose_name="项目阶段")
    version = models.CharField(max_length=30, null=True, blank=True, verbose_name="项目版本")
    progress = models.IntegerField(default=0, verbose_name="项目进度")
    desc = models.TextField(max_length=500, verbose_name="项目描述")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")
    """
    project_name = forms.CharField(label='项目名称', max_length=5, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    project_type = forms.CharField(label='项目类型', required=True)
    project_detail = forms.CharField(label='项目类型', required=True)

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
    {% block custom_title %}
    <title>Dashboard, Free HTML5 Admin Template</title>
    {% endblock %}
    <link href="http://www.jq22.com/jquery/bootstrap-3.3.4.css" rel="stylesheet">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="{% static 'css/templatemo_main.css' %}">

    {% block custom_css %}
    {% endblock %}
</head>
<body>
  <div class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <div class="logo"><h1>项目支撑系统 - {{ user.username }}</h1></div>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div>
  <div class="template-page-wrapper">
      <div class="navbar-collapse collapse templatemo-sidebar">
        <ul class="templatemo-sidebar-menu">
            <li>
            <form class="navbar-form">
              <input type="text" class="form-control" id="templatemo_search_box" placeholder="Search...">
              <span class="btn btn-default">Go</span>
            </form>
            </li>
            <li class="active"><a href="{% url 'index' %}"><i class="fa fa-home"></i>个人中心</a></li>
            <li class="sub open">
            <a href="javascript:">
              <i class="fa fa-database"></i> 项目管理 <div class="pull-right"><span class="caret"></span></div>
            </a>
            <ul class="templatemo-submenu">
                <li><a href="{% url 'project:own_project_list' %}">我的项目</a></li>
                <li><a href="{% url 'project:own_mission_list' %}">我的任务</a></li>
                <li><a href="{% url 'project:project_add' %}">新建项目</a></li>
                <li><a href="{% url 'project:test_tree' %}">日历控件测试</a></li>
                <li><a href="{% url 'project:test_tree' %}">动态添加条目测试</a></li>
                <li><a href="{% url 'formtest' %}">Form测试</a></li>

            </ul>
          </li>
            <li class="sub open">
            <a href="javascript:">
              <i class="fa fa-database"></i> 周报管理 <div class="pull-right"><span class="caret"></span></div>
            </a>
            <ul class="templatemo-submenu">
              <li><a href="#">我的周报</a></li>
              <li><a href="#">新建周报</a></li>
            </ul>
          </li>
            <li class="sub open">
            <a href="javascript:">
              <i class="fa fa-database"></i> 个人中心 <div class="pull-right"><span class="caret"></span></div>
            </a>
            <ul class="templatemo-submenu">
              <li><a href="#">我的文章</a></li>
              <li><a href="#">我的附件</a></li>
            </ul>
          </li>
        </ul>
      </div><!--/.navbar-collapse -->

      <div class="templatemo-content-wrapper">
          {% block custom_content %}
            {% endblock %}
      </div>
      <!-- Modal -->
      <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="myModalLabel">Are you sure you want to sign out?</h4>
            </div>
            <div class="modal-footer">
              <a href="sign-in.html" class="btn btn-primary">Yes</a>
              <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
          </div>
        </div>
      </div>
      <footer class="templatemo-footer">
        <div class="templatemo-copyright">

        </div>
      </footer>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <script src="{% static 'js/templatemo_script.js' %}"></script>
    <script type="text/javascript">
    // Line chart
    var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
    var lineChartData = {
      labels : ["January","February","March","April","May","June","July"],
      datasets : [
      {
        label: "My First dataset",
        fillColor : "rgba(220,220,220,0.2)",
        strokeColor : "rgba(220,220,220,1)",
        pointColor : "rgba(220,220,220,1)",
        pointStrokeColor : "#fff",
        pointHighlightFill : "#fff",
        pointHighlightStroke : "rgba(220,220,220,1)",
        data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
      },
      {
        label: "My Second dataset",
        fillColor : "rgba(151,187,205,0.2)",
        strokeColor : "rgba(151,187,205,1)",
        pointColor : "rgba(151,187,205,1)",
        pointStrokeColor : "#fff",
        pointHighlightFill : "#fff",
        pointHighlightStroke : "rgba(151,187,205,1)",
        data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
      }
      ]

    }

    window.onload = function(){
      var ctx_line = document.getElementById("templatemo-line-chart").getContext("2d");
      window.myLine = new Chart(ctx_line).Line(lineChartData, {
        responsive: true
      });
    };

    $('#myTab a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
    });

    $('#loading-example-btn').click(function () {
      var btn = $(this);
      btn.button('loading');
      // $.ajax(...).always(function () {
      //   btn.button('reset');
      // });
  });
  </script>
  {% block custom_js %}

  {% endblock %}
</body>
</html>

templates/formtest.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_title %}
    <title>新建项目</title>
{% endblock %}

{% block custom_content %}
        <div class="templatemo-content">
          <ol class="breadcrumb">
            <li><a href="{% url 'index' %}">首页</a></li>
            <li class="active">新建项目</li>
          </ol>
          <h1>新项目</h1>
          <p class="margin-bottom-15">完成信息填写以快速创建项目</p>
          <div class="row">
            <div class="col-md-12">
              <form role="form" id="templatemo-preferences-form" method="post" action="{% url 'project:project_add' %}">
                {% csrf_token %}
                {{ new_project_form.non_field_errors }}
                <div class="row">
                  <div class="col-md-6 margin-bottom-15">
{#                      <label for="{{ new_project_form.project_name.id_for_label }}" class="control-label">{{ new_project_form.project_name.label }}</label>#}
{#                      <br>#}
{#                    <input type="text" class="form-control" id="projectName" name="projectName" value="">#}
{#                      {{ new_project_form.project_name }}#}
                      {{ new_project_form.project_name.errors }}<br>
                      {{ new_project_form.project_name.label }}:<br>
                      {{ new_project_form.project_name }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 margin-bottom-15">
                    <label for="projectManager">项目经理</label>
                    <input type="text" class="form-control" id="projectManager" value="{{ request.user.username }}" name="projectManager" disabled>
                  </div>
                  <div class="col-md-6 margin-bottom-15">
                  </div>
                </div>
                <div class="row">
                <div class="col-md-6 margin-bottom-15">
                  <label for="projectType">项目类型</label>
                  <select class="form-control margin-bottom-15" id="projectType" name="projectType">
                    <option>金融产品</option>
                    <option>电信产品</option>
                    <option>物联网产品</option>
                  </select>
                  <label for="projectStuffs">选择人员</label>
                  <select multiple class="form-control" id="projectStuffs" name="projectStuffs">
                      {% for user in all_users %}
                          <option>{{ user.username }}</option>
                      {% endfor %}
                  </select>
                </div>
              </div>
                <div class="row">
                  <div class="col-md-12 margin-bottom-15">
                      <label for="projectDetail">项目简述</label>
                      <textarea class="form-control" rows="3" id="projectDetail" name="projectDetail"></textarea>
                  </div>
              </div>
                <div class="row">
                <div class="col-md-12 margin-bottom-30">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" id="exampleInputFile">
                  <p class="help-block">You can upload file here.</p>
                </div>
              </div>
                <div class="row templatemo-form-buttons">
                <div class="col-md-12">
                  <button type="submit" class="btn btn-primary">提交</button>
                  <button type="reset" class="btn btn-default">清空</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        </div>
{% endblock %}

templates/main_panel.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_title %}
    <title>主面板</title>
{% endblock %}

{% block custom_content %}
    <div class="templatemo-content">
          <ol class="breadcrumb">
            <li><a href="{% url 'index' %}">首页</a></li>
            <li class="active">主面板</li>
          </ol>
          <div class="row margin-bottom-30">
            <div class="col-md-12">
              <ul class="nav nav-pills">
                <li class="active"><a href="#">当前项目<span class="badge">42</span></a></li>
                <li class="color1"><a href="#">完成项目<span class="badge">107</span></a></li>
                <li class="color2"><a href="#">周报<span class="badge">3</span></a></li>
              </ul>
            </div>
          </div>
        <div class="row">
            <div class="col-md-12">
              <div class="table-responsive">
                <h4 class="margin-bottom-15">最近周报</h4>
                <table class="table table-striped table-hover table-bordered">
                  <thead>
                    <tr>
                      <th>标题</th>
                      <th>编写时间</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for my_weekreport in all_my_weekreports %}
                      <tr>
                          <td>{{ my_weekreport.topic }}</td>
                          <td>{{ my_weekreport.add_time }}</td>
                          <td>
                            <!-- Split button -->
                            <div class="btn-group">
                              <button type="button" class="btn btn-info">操作</button>
                              <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                <li><a href="#">编辑</a></li>
                                <li><a href="#">普通查看</a></li>
                              </ul>
                            </div>
                          </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <div class="table-responsive">
                <h4 class="margin-bottom-15">最近项目</h4>
                <table class="table table-striped table-hover table-bordered">
                  <thead>
                    <tr>
                      <th>项目名</th>
                      <th>项目成员</th>
                      <th>类型</th>
                      <th>状态</th>
                      <th>当前版本</th>
                      <th>创建时间</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for project in all_my_projects %}
                    <tr>
                        <td>{{ project.name }}</td>
                        <td>{{ project.get_this_project_all_staffs }}</td>
                        <td>{{ project.get_field_display }}</td>
                        <td>{{ project.get_status_display }}</td>
                        <td>{{ project.version }}</td>
                        <td>{{ project.add_time }}</td>
                        <td>
                        <!-- Split button -->
                        <div class="btn-group">
                          <button type="button" class="btn btn-info">操作</button>
                          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                          </button>
                          <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'project:project_detail' project.id %}">查看</a></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
        </div>
    </div>
{% endblock %}